name: 'Install Theos'
description: 'Install Theos and prepare it for building projects'
inputs:
  theos-dir:
    description: 'Where to install Theos (relative to the repo workspace itself)'
    required: false
    default: theos
  theos-src:
    description: 'Where to fetch Theos from (git URL)'
    required: false
    default: 'https://github.com/theos/theos'
  theos-sdks:
    description: 'Where to get the SDKs from (git URL)'
    required: false
    default: 'https://github.com/theos/sdks'
runs:
  using: "composite"
  steps:
    - name: prepare environment
      shell: bash
      run: |
        brew install ldid make
        echo "THEOS=$GITHUB_WORKSPACE/${{ inputs.theos-dir }}" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/opt/make/libexec/gnubin" >> $GITHUB_ENV

    - name: get theos
      shell: bash
      run: |
        git clone ${{ inputs.theos-src }} ${{ github.workspace }}/${{ inputs.theos-dir }} --recursive

    - name: get sdks
      shell: bash
      run: |
        cd ${{ github.workspace }}/${{ inputs.theos-dir }}/sdks
        git init
        git remote add origin ${{ inputs.theos-sdks }}
        git fetch origin --depth=1
        git reset --hard origin/master || git reset --hard origin/main
